// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateMovie(ctx context.Context, title string) (Movie, error)
	GetMovie(ctx context.Context, id int64) (Movie, error)
	ListMovies(ctx context.Context) ([]Movie, error)
	UpdateMovie(ctx context.Context, id int64) (Movie, error)
}

var _ Querier = (*Queries)(nil)
